Move structure verification to Lint job

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -34,48 +34,11 @@ jobs:
         npm run env | grep npm_package_version >> $GITHUB_ENV
     - run: |
         echo Workflow triggered by event ${{ github.event_name }}
-    - name: Install grep and find
-      run: sudo apt-get install grep findutils
-    
-    - name: Create non-minified js files
-      run: npm run build:js -- --environment NO_MINIFY
-      env:
-        YT_API_KEY: ${{ secrets.YOUTUBE_KEY }}
-    - name: Verify no debug artifacts
-      run: |
-        dev=$(grep --color=always "devClone\|devExport\|(()=>{})" $(find extension-dist -name "*.js") || echo "")
-        if [ -n "$dev" ]; then
-          echo "::group::Invalid statements"
-          echo "$dev"
-          echo "::endgroup::"
-          echo "::error ::Found statements that shouldn't be in the production build!"
-          exit 1
-        fi
-      shell: bash
     
     - name: Build
       run: npm run build:all # does not run tests
       env:
         YT_API_KEY: ${{ secrets.YOUTUBE_KEY }}
-    
-    - name: Verify directory structure
-      run: |
-        locales=$(find extension-dist/_locales -not -name "*.json" -type f)
-        scripts=$(find extension-dist/scripts -not -name "*.js" -type f)
-        styles=$(find extension-dist/styles -not -name "*.css" -type f)
-        if [ -n "$locales" ] || [ -n "$scripts" ] || [ -n "$styles" ]; then
-          echo "::group::Files found"
-          echo -e "\nIn _locales"
-          echo "$locales"
-          echo -e "\nIn scripts"
-          echo "$scripts"
-          echo -e "\nIn styles"
-          echo "$styles"
-          echo "::endgroup::"
-          echo "::error ::Found files that do not belong!"
-          exit 1
-        fi
-      shell: bash
 
     - name: Archive extension
       uses: actions/upload-artifact@v2
@@ -268,6 +231,27 @@ jobs:
     - name: Find version
       run: |
         npm run env | grep npm_package_version >> $GITHUB_ENV
+
+    - name: Install grep and find
+      run: sudo apt-get install grep findutils
+    
+    - name: Create non-minified files
+      run: npm run build:all -- --environment NO_MINIFY
+      env:
+        YT_API_KEY: ${{ secrets.YOUTUBE_KEY }}
+    - name: Verify no debug artifacts
+      run: |
+        dev=$(grep --color=always "devClone\|devExport\|(()=>{})" $(find extension-dist -name "*.js") || echo "")
+        if [ -n "$dev" ]; then
+          echo "::group::Invalid statements"
+          echo "$dev"
+          echo "::endgroup::"
+          echo "::error ::Found statements that shouldn't be in the production build!"
+          exit 1
+        fi
+      shell: bash
+    - name: Run addon linter on non-minified
+      run: npm run lint:ext
     
     - name: Get build files
       uses: actions/download-artifact@v2
@@ -275,6 +259,24 @@ jobs:
         name: enhancer_for_nebula-${{ env.npm_package_version }}
         path: |
           extension-dist/
-        
+
+    - name: Verify directory structure
+      run: |
+        locales=$(find extension-dist/_locales -not -name "*.json" -type f)
+        scripts=$(find extension-dist/scripts -not -name "*.js" -type f)
+        styles=$(find extension-dist/styles -not -name "*.css" -type f)
+        if [ -n "$locales" ] || [ -n "$scripts" ] || [ -n "$styles" ]; then
+          echo "::group::Files found"
+          echo -e "\nIn _locales"
+          echo "$locales"
+          echo -e "\nIn scripts"
+          echo "$scripts"
+          echo -e "\nIn styles"
+          echo "$styles"
+          echo "::endgroup::"
+          echo "::error ::Found files that do not belong!"
+          exit 1
+        fi
+      shell: bash
     - name: Run linters
       run: npm run lint
